# Generated by Django 4.1.3 on 2022-11-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greensapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='post_type',
            new_name='category',
        ),
    ]
