# Generated by Django 4.1.3 on 2022-11-07 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('greensapp', '0006_remove_social_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='likes',
            field=models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
