# Generated by Django 4.1.3 on 2022-11-07 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('greensapp', '0007_alter_social_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='likes',
            field=models.ManyToManyField(default=0, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
