# Generated by Django 4.1.3 on 2022-11-08 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('greensapp', '0010_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='date_update',
        ),
        migrations.AlterField(
            model_name='social',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='greensapp.posttype'),
        ),
        migrations.AlterField(
            model_name='social',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
