# Generated by Django 4.1.3 on 2022-11-08 19:41

from django.db import migrations, models
import greensapp.formatchecker


class Migration(migrations.Migration):

    dependencies = [
        ('greensapp', '0011_remove_social_date_update_alter_social_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_reply',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_replied',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='file',
            field=greensapp.formatchecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='static/media'),
        ),
    ]
