# Generated by Django 4.1.3 on 2022-11-08 19:43

from django.db import migrations
import greensapp.formatchecker


class Migration(migrations.Migration):

    dependencies = [
        ('greensapp', '0012_comment_is_reply_comment_message_replied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='file',
            field=greensapp.formatchecker.ContentTypeRestrictedFileField(blank=True, null=True, upload_to='media'),
        ),
    ]
