# Generated by Django 4.1.3 on 2022-11-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensapp', '0015_maps_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='social',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='lat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='social',
            name='long',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Maps',
        ),
    ]
