# Generated by Django 4.0.4 on 2022-11-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensapp', '0016_social_address_social_lat_social_long_delete_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='category',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
