# Generated by Django 4.0.4 on 2022-11-18 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greensapp', '0017_alter_social_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='lat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='social',
            name='long',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
